### ISSUE TITLE
Installing current bcdata version into virtenv

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/bcdata#3]
@smnorris, I'll put this here so it doesn't clutter your repo.  As usual, I am asking you questions on the weekend and I hope it goes without saying that I am 100% ok if you don't answer at all until you are back "working" if you are taking time off.... I'll put it down here for now for when you are on the keys. 

I have a feeling this is a silly question, but I have a knack for chasing rabbits down holes that go for days so I'll throw this out to you in case you might save me a long and dark chase. 

I want to install the new version of `bcdata`  that records the download date in `public.bcdata`.  I have `pip uninstall bcdata` the original version from the `bcfp` virtual environment which is at 

`~/anaconda3/envs/bcfp`

I can see that all the packages in `requirements.txt` of `bcdata` are still there in `bcfp`.

What is the best way to install the cloned version of `bcdata` into the `bcfp` virt env?  Currently, `bcdata` is at `~/scripts/bcdata` but I could clone it into `~/anaconda3/envs/bcfp` and then `cd` into there and run `python setup.py`?  Or do I need to start with a fresh directory and rebuild the virt env maybe?

Really excited about every piece of this puzzle that is coming together on my machine. Thanks so much for being such a ninja! 🔑

**Comment by smnorris** [comment]
No need to call `setup.py` directly, `pip` will do it for you:
https://github.com/smnorris/bcdata#development-and-testing
```
(your_env)$ pip uninstall bcdata
(your_env)$ git clone git@github.com:smnorris/bcdata.git
(your_env)$ cd bcdata
(your_env)$ pip install .
```

**Comment by NewGraphEnvironment** [comment]
👍🏼

**Comment by NewGraphEnvironment** [comment]
oh god. So sorry to bug you with this.  Not sure why `bcdata `and I have such a hard time getting along.  I ran into some issues where things weren't working again (somehow related to nested virtual envs - I think I am doing something wrong with my initial conda setups). Anyway, I was able to resolve by deactivating out of all my conda envs then activating into `bcfp`.  However, I uninstalled `bcdata` as part of the troubleshooting process and upon reinstallation I can't seem to get it to work at all.... Can you have a look at this workflow and resulting error messages to see if there is something in it that tips you off on an easy fix?  All I can think of to do is to erase then rebuild the `bcfp` virt env from scratch again and that might take me another very long time. 


```
(bcfp) newgraph@MSI:~/scripts$ pip uninstall bcdata
Found existing installation: bcdata 0.4.4.dev0
Uninstalling bcdata-0.4.4.dev0:
  Would remove:
    /home/newgraph/anaconda3/envs/bcfp/bin/bcdata
    /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/bcdata-0.4.4.dev0.dist-info/*
    /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/bcdata/*
Proceed (y/n)? y
  Successfully uninstalled bcdata-0.4.4.dev0
(bcfp) newgraph@MSI:~/scripts$ rm -rf bcdata
(bcfp) newgraph@MSI:~/scripts$ ls
backupr  bcfishobs  bcfishpass  fwapg  geobc  python-rasterstats  rasterio  setups
(bcfp) newgraph@MSI:~/scripts$ git clone https://github.com/NewGraphEnvironment/bcdata.git
Cloning into 'bcdata'...
remote: Enumerating objects: 152, done.
remote: Counting objects: 100% (152/152), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 1114 (delta 92), reused 98 (delta 40), pack-reused 962
Receiving objects: 100% (1114/1114), 251.13 KiB | 1.18 MiB/s, done.
Resolving deltas: 100% (649/649), done.
(bcfp) newgraph@MSI:~/scripts$ cd bcdata
(bcfp) newgraph@MSI:~/scripts/bcdata$ pip install .
Processing /home/newgraph/scripts/bcdata
Requirement already satisfied: click<8,>=7.0 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from bcdata==0.4.4.dev0) (7.1.2)
Requirement already satisfied: cligj>=0.5 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from bcdata==0.4.4.dev0) (0.7.1)
Requirement already satisfied: pgdata>=0.0.12 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from bcdata==0.4.4.dev0) (0.0.12)
Requirement already satisfied: requests in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from bcdata==0.4.4.dev0) (2.25.1)
Requirement already satisfied: owslib in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from bcdata==0.4.4.dev0) (0.23.0)
Requirement already satisfied: rasterio in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from bcdata==0.4.4.dev0) (1.2.1)
Requirement already satisfied: geopandas in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from bcdata==0.4.4.dev0) (0.9.0)
Requirement already satisfied: geoalchemy2 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from pgdata>=0.0.12->bcdata==0.4.4.dev0) (0.8.4)
Requirement already satisfied: alembic in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from pgdata>=0.0.12->bcdata==0.4.4.dev0) (1.5.6)
Requirement already satisfied: sqlalchemy in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from pgdata>=0.0.12->bcdata==0.4.4.dev0) (1.4.2)
Requirement already satisfied: sqlalchemy-utils in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from pgdata>=0.0.12->bcdata==0.4.4.dev0) (0.36.8)
Requirement already satisfied: psycopg2-binary in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from pgdata>=0.0.12->bcdata==0.4.4.dev0) (2.8.6)
Requirement already satisfied: Mako in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from alembic->pgdata>=0.0.12->bcdata==0.4.4.dev0) (1.1.4)
Requirement already satisfied: python-editor>=0.3 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from alembic->pgdata>=0.0.12->bcdata==0.4.4.dev0) (1.0.4)
Requirement already satisfied: python-dateutil in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from alembic->pgdata>=0.0.12->bcdata==0.4.4.dev0) (2.8.1)
Requirement already satisfied: greenlet!=0.4.17 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from sqlalchemy->pgdata>=0.0.12->bcdata==0.4.4.dev0) (1.0.0)
Requirement already satisfied: pandas>=0.24.0 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from geopandas->bcdata==0.4.4.dev0) (1.2.3)
Requirement already satisfied: fiona>=1.8 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from geopandas->bcdata==0.4.4.dev0) (1.8.18)
Requirement already satisfied: pyproj>=2.2.0 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from geopandas->bcdata==0.4.4.dev0) (3.0.1)
Requirement already satisfied: shapely>=1.6 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from geopandas->bcdata==0.4.4.dev0) (1.7.1)
Requirement already satisfied: attrs>=17 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from fiona>=1.8->geopandas->bcdata==0.4.4.dev0) (20.3.0)
Requirement already satisfied: certifi in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from fiona>=1.8->geopandas->bcdata==0.4.4.dev0) (2020.12.5)
Requirement already satisfied: click-plugins>=1.0 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from fiona>=1.8->geopandas->bcdata==0.4.4.dev0) (1.1.1)
Requirement already satisfied: six>=1.7 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from fiona>=1.8->geopandas->bcdata==0.4.4.dev0) (1.15.0)
Requirement already satisfied: munch in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from fiona>=1.8->geopandas->bcdata==0.4.4.dev0) (2.5.0)
Requirement already satisfied: pytz>=2017.3 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from pandas>=0.24.0->geopandas->bcdata==0.4.4.dev0) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from pandas>=0.24.0->geopandas->bcdata==0.4.4.dev0) (1.20.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from Mako->alembic->pgdata>=0.0.12->bcdata==0.4.4.dev0) (1.1.1)
Requirement already satisfied: pyyaml in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from owslib->bcdata==0.4.4.dev0) (5.4.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from requests->bcdata==0.4.4.dev0) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from requests->bcdata==0.4.4.dev0) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from requests->bcdata==0.4.4.dev0) (2.10)
Requirement already satisfied: snuggs>=1.4.1 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from rasterio->bcdata==0.4.4.dev0) (1.4.7)
Requirement already satisfied: affine in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from rasterio->bcdata==0.4.4.dev0) (2.3.0)
Requirement already satisfied: pyparsing>=2.1.6 in /home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages (from snuggs>=1.4.1->rasterio->bcdata==0.4.4.dev0) (2.4.7)
Building wheels for collected packages: bcdata
  Building wheel for bcdata (setup.py) ... done
  Created wheel for bcdata: filename=bcdata-0.4.4.dev0-py3-none-any.whl size=17732 sha256=2ddffe20c35529d5c01a4a3716454c7fd20aa701327adf65e396bd2b3c0e9639
  Stored in directory: /tmp/pip-ephem-wheel-cache-yxaovjh5/wheels/e6/37/65/a34374e976d8e316a0c42c092bd46fc92728b62b78f5091ac2
Successfully built bcdata
Installing collected packages: bcdata
Successfully installed bcdata-0.4.4.dev0
(bcfp) newgraph@MSI:~/scripts/bcdata$ bcdata --help
Traceback (most recent call last):
  File "/home/newgraph/anaconda3/envs/bcfp/bin/bcdata", line 5, in <module>
    from bcdata.cli import cli
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/bcdata/cli.py", line 20, in <module>
    import pgdata
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/pgdata/__init__.py", line 9, in <module>
    from pgdata.database import Database
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/pgdata/database.py", line 19, in <module>
    from .table import Table
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/pgdata/table.py", line 20, in <module>
    from sqlalchemy_utils import LtreeType
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/home/newgraph/anaconda3/envs/bcfp/lib/python3.9/site-packages/sqlalchemy/orm/query.py)
```

Although maybe not that relevant since I can't seem to run `bcdata` at all... when I `printenv` some info is:

```
DATABASE_URL=postgresql://newgraph:postgres@localhost:5434/postgis
PGPORT=5434
PGPASSWORD=postgres
PGUSER=newgraph
PGDATABASE=postgis
PGOGR=host= user= dbname= password= port=
```

**Comment by smnorris** [comment]
If I understand correctly, you're using both `conda` and `virtualenv` to manage environments.
You need to choose one and stick with it, they aren't going to work nicely together.

**Comment by NewGraphEnvironment** [comment]
hmm.  Not sure I understand the difference.  Is it a `conda` vs. `anaconda` thing?  It seems like there is a `base` environment that my terminal defaults to when I start it up.  Not sure why.  When i don't `conda deactivate base` out of it I have run into issues.  I think I am missing somehting.

**Comment by smnorris** [comment]
Are you using `virtualenv` command?

**Comment by NewGraphEnvironment** [comment]
I don't think so. sounds familiar though.  I wonder if I mucked something up at the very beginning and I am still paying for it. Confusing.

**Comment by smnorris** [comment]
I don't think so, it should be ok. It is confusing because there are too many ways to do the same thing and they don't work well together. I'll tweak the bcdata environment.yml just to make sure that isn't the issue

**Comment by NewGraphEnvironment** [comment]
> No need to call `setup.py` directly, `pip` will do it for you:
> https://github.com/smnorris/bcdata#development-and-testing
> 
> ```
> (your_env)$ pip uninstall bcdata
> (your_env)$ git clone git@github.com:smnorris/bcdata.git
> (your_env)$ cd bcdata
> (your_env)$ pip install .
> ```

i didn't load that env.... I have loaded it into the `bcfp` env as per above.  I am using it as part of the process to build `bcfishpass`.

**Comment by smnorris** [comment]
I've tweaked the environment.yml to make sure it gets everything from `conda` (rather than `pip`) apart from `bcdata` itself.  Starting fresh with a new environment:

```
git clone https://github.com/smnorris/bcdata.git
cd bcdata
conda create -f environment.yml
conda activate bcdataenv
pip install .
```

**Comment by NewGraphEnvironment** [comment]
so then I would install everyting from `bcfishpass` into there and run those scripts in `bcdataenv`?

**Comment by smnorris** [comment]
Yes, add the missing requirements into that yml file
```
rasterstats
csvkit
jq
parallel
```

**Comment by smnorris** [comment]
or install manually, doesn't matter

**Comment by smnorris** [comment]
I've added an (untested) environment.yml file to bcfishpass as well. Conda can handle the environment variables too: https://github.com/smnorris/bcfishpass/blob/main/environment.yml. For your case you'd have to 
- remove the bcdata line and pip install the latest after installing everything else
- edit the environment variables to point to your db

**Comment by NewGraphEnvironment** [comment]
ok.  Ya, nothing seemed to work with that last attempt so I am in the process of rebuilding the `bcfp` from scratch. I'll try wiht the yml next time

**Comment by smnorris** [comment]
I'll probably get `bcdata` onto conda-forge at some point (haven't looked into it yet) but first I want to remove the `pgdata` dependency. And having it on conda wouldn't help you anyway, you want the latest and greatest.

**Comment by NewGraphEnvironment** [comment]
same issues with both attempts... I am going to try a couple more things then look at nuking anaconda and trying to install conda again. If you were starting fresh which conda installation do you think you would use and where would you get it from? Sorry for all the questions.  Not sure what happened. Everything was working great for a little bit there....

**Comment by smnorris** [comment]
I've only used miniconda via installers here https://docs.conda.io/en/latest/miniconda.html

**Comment by NewGraphEnvironment** [comment]
ok.  `bcfpenv` works for `rasterio` plugin (that was an issue on this last headache round) but `bcdata --help` still throws the same errors... Any chance you might be able to confirm that `bcdata` works in `bcfpenv` on your machine before I chase this too much longer?

**Comment by smnorris** [comment]
hmm, nope. 
```
$ cd bcfishpass
$ conda env create -f environment.yml
$ conda activate bcfpenv
$ bcdata --help
Traceback (most recent call last):
  File "/Users/snorris/miniconda3/envs/bcfpenv/bin/bcdata", line 5, in <module>
    from bcdata.cli import cli
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/bcdata/cli.py", line 20, in <module>
    import pgdata
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/pgdata/__init__.py", line 9, in <module>
    from pgdata.database import Database
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/pgdata/database.py", line 19, in <module>
    from .table import Table
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/pgdata/table.py", line 20, in <module>
    from sqlalchemy_utils import LtreeType
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/Users/snorris/miniconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py)
```

**Comment by smnorris** [comment]
I'll look into it now, maybe I'll have to remove the `pgdata` dependency sooner rather than later.

**Comment by NewGraphEnvironment** [comment]
ok. thanks for checking and looking into it. 

moving to other things for a bit. 

Thanks for that yml! it sure speeds things up and will be super useful down the road for other applications.

**Comment by smnorris** [comment]
I've updated by pinning to specific versions of sqlalchemy and sqlalchemy add-ons. Works now. 

I am not sure what has changed but sqlalchemy and the add-ons are are dependencies that can be avoided if I clean things up.

**Comment by smnorris** [comment]
https://github.com/smnorris/bcfishpass/commit/a4682f2396b8ae55619f6343546b2e854340c5f0#diff-9efd195f4e9bfb79ccd456a1d8370fafcc4bcb0b00ea3799222667d2ae818533

**Comment by smnorris** [comment]
issue is upstream here https://github.com/kvesteri/sqlalchemy-utils/issues/505

**Comment by NewGraphEnvironment** [comment]
the doctor is in!! 🧑‍⚕️ Thank you!  Another testament to the beauty of virt envs and issue tracking I guess. Back at it.

**Comment by smnorris** [comment]
Also a testament to reducing the list of dependencies...

**Comment by NewGraphEnvironment** [comment]
I'm absolutely horrible for that on every single project it seems.
